### ISSUE TITLE
`make clean` deletes the source code

### ISSUE THREAD

**Issue by electronstudio** [libretro/skeletor#1] opened 2022-01-30 21:53 UTC
On Linux, if you type:

    make clean

The output is:

    rm -f  ./libretro.c skeleton_libretro.so

and the C source code is deleted.

**Comment by gouchi** [comment] 2024-03-05 14:18
Hi,

I can't reproduce this issue using [latest commit](https://github.com/libretro/skeletor/commit/149b81a51956abe8f5ef27ee0a36a32fab1ce673).

```
make
CC libretro.c
LD skeleton_libretro.so
```

```
make clean
rm -f ./libretro.o  skeleton_libretro.so
```

So if I don't reproduce the issue anymore, please close this issue.

Thank you.

**Closed as completed** 2024-03-05 14:27 UTC
